### ISSUE TITLE
Port in use

### ISSUE THREAD

**Issue by charredchar** [MagicPhoenix/EIS#3]
Port `8080` is already in use on my install. And considering pretty much all webcam software for 3D printers will use `8080` it is probably best to either use something else or add an option during install to use something else.

I attempted to work around this by myself by compiling it with a modified `main.go` file but I get an error.

```Now using go1.18
pi@fluiddpi:~/EIS $ go mod tidy
-bash: /home/pi/.g/go/bin/go: cannot execute binary file: Exec format error
pi@fluiddpi:~/EIS $ g use 1.18
pi@fluiddpi:~/EIS $

**Comment by smolz** [comment]
in the same boat.

**Comment by zapl** [comment]
`Exec format error` probably means you installed go for `armv64` (i.e. 64 bit) on a pi / install that doesn't support that.

```
pi@voron:~/EIS $ go
-bash: /home/pi/.g/go/bin/go: cannot execute binary file: Exec format error
pi@voron:~/EIS $ g uninstall 1.18
Uninstalled go1.18
pi@voron:~/EIS $ g install 1.18
1) *go1.18.linux-arm64.tar.gz
2)  go1.18.linux-armv6l.tar.gz
Please select the package you want to install.
2
Downloading 100% [===============] (105/105 MB, 11 MB/s)
Computing checksum with SHA256
Checksums matched
Now using go1.18
pi@voron:~/EIS $ go mod tidy
go: downloading gorm.io/gorm v1.25.0
go: downloading gorm.io/driver/sqlite v1.5.0
....
``

**Comment by charredchar** [comment]
I'll take a look but if I recall I was able to get it running by changing the port in the source before installing then it worked without an issue.

**Comment by charredchar** [comment]
Please disregard my previous statement, I confused myself on what happened.
You are correct, the issue was that it installed `arm64` instead of `armv6l`. This happens if you copy and paste the commands as a space at the end gets interpreted as an enter automatically and installs the default selection.
I did get this working myself previously but I forgot how I did it. 😅 
I would still highly recommend having an option to change the port, either a setting file or an argument when running, so the end user can change it easily. Especially because pretty much all webcam services will use `8080` by default.

**Comment by charredchar** [comment]
Well, now I don't know the issue I am having.

I had to reinstall the system, I use the Pi Imager and used the 32bit PiOS. Now I am getting the following.

```
char@fluiddpi:~/EIS $ sudo nano main.go
char@fluiddpi:~/EIS $ wget -qO- https://raw.githubusercontent.com/voidint/g/master/install.sh | bash
[1/3] Downloading https://github.com/voidint/g/releases/download/v1.5.2/g1.5.2.linux-arm64.tar.gz
[2/3] Install g to the /home/char/.g/bin
[3/3] Set environment variables

To configure your current shell, run:
source "/home/char/.g/env"
char@fluiddpi:~/EIS $ source /home/char/.g/env
char@fluiddpi:~/EIS $ g install 1.18
Downloading 100% [===============] (104/104 MB, 4.1 MB/s)
Computing checksum with SHA256
Checksums matched
Now using go1.18
char@fluiddpi:~/EIS $ go mod tidy
-bash: /home/char/.g/go/bin/go: No such file or directory
char@fluiddpi:~/EIS $ g -v
g version 1.5.2
build: 2023-09-05T21:47:25+08:00
branch: release/1.5.2
commit: dd615e5d
char@fluiddpi:~/EIS $
```

It seems it won't let me select a different version. I am currently troubleshooting my way through this but relying on `g install` is going to cause problems unless we can specify exactly what we want.

**Comment by CD1010** [comment]
Crowsnest uses port 8080.  Configure it to use 8081 in crowsnest.conf and fix the url to webcam2.  That fixes it.

**Comment by charredchar** [comment]
> Crowsnest uses port 8080. Configure it to use 8081 in crowsnest.conf and fix the url to webcam2. That fixes it.

Which breaks other things...
I'll just stop using it.

**Comment by CD1010** [comment]
> > Crowsnest uses port 8080. Configure it to use 8081 in crowsnest.conf and fix the url to webcam2. That fixes it.
> 
> Which breaks other things... I'll just stop using it.

Then just pick another port.  You have 65536 to choose from. ( Not 80 )
